spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital?characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: asd123...
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.test.elasticsearchdemo.domain

logging:
  level:
    com.app.mapper: debug


server:
  port: 9090

